config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to:"posts#index"
  resources :posts do
    resources :likes, only:[:create, :destroy]
    collection do
      get 'search', 'ranking'
    end
  end
  resources :users, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/music.rb
class Music < ApplicationRecord
  has_many :playlists, dependent: :destroy
  has_many :posts, through: :playlists, dependent: :destroy
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :post
  belongs_to :music
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable 
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :musics, through: :playlists
  
  with_options presence: true do
    validates :title
    validates :image
    validates :url, format: {with: /https?:\/\/open.spotify.com\/playlist\/[a-zA-Z0-9]{22}\?si=[a-zA-Z0-9]{16}/}
  end
  
  def self.search(search)
    if search != ""
      post = Post.where('title LIKE(?)', "%#{search}%")
      tag = Post.tagged_with([search], wild: true, any: true)
      music = Post.joins(:musics).where('track LIKE(?)', "%#{search}%")
      
      post | tag | music
    end
  end
  
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/post_music.rb
class PostMusic
  include ActiveModel::Model
  attr_accessor :title, :url, :image, :user_id, :track, :tag_list

  with_options presence: true do
    validates :title
    validates :image
    validates :url, format: {with: /https?:\/\/open.spotify.com\/playlist\/[a-zA-Z0-9]{22}\?si=[a-zA-Z0-9]{16}/}
  end

  def sp_list(url)
    if url.match("https://open.spotify.com/playlist/")
      @musics =[]
      music_1 = []
      id = url.slice(34..55)
      require 'rspotify'
      RSpotify.authenticate(ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"])
      playlist = RSpotify::Playlist.find_by_id(id)
      music_list = playlist.tracks
      music_list.length.times do |i|
        music_1 << music_list[i]
      end
      music_1.length.times do |i|
        @musics << music_1[i].name
      end
      return @musics
    end
  end

  def save
    post = Post.create(title: title, url: url, user_id: user_id, image: image, tag_list: tag_list )
    sp_list(url)
    @musics.uniq.each do |track|
      music = Music.where(track: track).first_or_initialize
      if music.save
      Playlist.create(post_id: post.id, music_id: music.id)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  with_options presence: true do
  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message:"半角英数字を含む6文字以上のパスワードにしてください"}
  validates :name, uniqueness: { case_sensitive: false }
  end
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :image])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post
  def create
    like = @post.likes.new(user_id: current_user.id)
    like.save
  end

  def destroy
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :ranking, :search]
  before_action :post_set, only:[:show, :edit, :update, :destroy]
  before_action :move_to_index, only:[:edit, :destroy]
  
  def index
    @posts = Post.all.includes(:user).order(created_at: :desc).page(params[:page]).per(6)
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").page(params[:page]).per(6)
    end
  end

  def new
    @post = PostMusic.new
  end

  def create
    @post = PostMusic.new(post_params)
    if @post.valid?
      @post.save
      flash[:notice] = '投稿が完了しました'
      redirect_to root_path
    else
      flash.now[:alert] = '無効なURL、あるいは入力されていない項目があります'
      render :new
    end
  end

  def show
    
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    end
  end

  def search
    @posts = Post.search(params[:keyword])
    if @posts.present?
      @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(6)
    end
  end

  def ranking
    @like_posts = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
    @tags = Post.tag_counts_on(:tags).most_used(5)
  end

  private

  def post_params
    params.require(:post_music).permit(:title, :url, :image, :tag_list).merge(user_id: current_user.id)
  end

  def post_set
    @post = Post.find(params[:id])
  end

  def move_to_index
    if current_user.id != @post.user_id
      redirect_to root_path
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
    @likes = @user.like_posts

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  

  def sp_list_full(url)
    if url.match("https://open.spotify.com/playlist/")
      musics =[]
      id = url.slice(34..55)
      require 'rspotify'
      RSpotify.authenticate(ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"])
      playlist = RSpotify::Playlist.find_by_id(id)
      music_list = playlist.tracks(limit:40)
      music_list.length.times do |i|
        musics << music_list[i]
        end
        return musics
      end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharemusic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/header"%>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if post.liked_by?(current_user) %>
   <%= link_to post_like_path(post_id:post.id, id: current_user.id), method: :DELETE, remote: true do %>
   <i class="fa fa-heart fa-2x" aria-hidden="true" style="color: red;"></i>
   <span class="like"><%= post.likes.count %></span>
   <% end %>
<% else %>
  <%= link_to post_likes_path(post_id:post.id, id: current_user.id), method: :POST, remote: true do %>
  <i class="fa fa-heart fa-2x" aria-hidden="true" style="color: gray;"></i>
  <span class="like"><%= post.likes.count %></span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_btn_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");
$('#like_btn_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_btn_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");
$('#like_btn_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_contents.html.erb
<div class = "contents">
  <% posts.each do |post|%>
      <div class="content">
        <div class="top-content">
          <h2><%= post.title%></h2>
          <%= link_to "作成者：#{post.user.name}", user_path(post.user_id), class:"user"%></a>
        </div>
        <div class="play-list">
          <div class="left-contents">
              <%= link_to (image_tag (post.image),class: "list-img"), post_path(post.id) %>
            <% post.tag_list.each do |tag| %>
              <div class="hash-name">
                <span class = "hash" >#</span><%= link_to tag, root_path(tag_name: tag), class:"user" %>
              </div>
            <%end%>
          </div>
          <ul class="musics">
          <% post.musics.first(10).each do |music|%>
            <li><%= music.track %></li>
          <% end %>
          </ul>
        </div>
        
        <% if user_signed_in?%>
        <div class="favorite">
          <div id="likes_btn_<%=post.id%>" >
            <%= render "likes/like", post: post%>
          </div>
        </div>
        <%else%>
        <div class="favorite">
          <i class="fa fa-heart fa-2x" aria-hidden="true" style="color: gray;"></i>
          <span class="like"><%= post.likes.count %></span>
        </div>
        <%end%>
        
      </div>
    <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, url: url, local: true  do |form| %>
<div class="form">
  <p>プレイリストのタイトル <span class = "required">　*必須</span></p>
  <%= form.text_field :title, class:"post-form" ,placeholder:"タイトル"%>
  <p>Spotifyで作成したプレイリストのURL<span class = "required">　*必須</span></p>
  <%= form.text_field :url, rows: "1", class:"post-form",placeholder:"https://open.spotify.com/playlist/から始まるURL" %>
  <p>ハッシュタグを入力してください<span class="descroption">(複数入力する場合「,」で区切ってください)</p>
  <%= form.text_field :tag_list, rows: "1", class:"post-form",placeholder:"tag1, tag2" %>
  <div id= "search-result"></div>
  <p>プレイリストのイメージ画像<span class = "required">　*必須</span></p>
  <%= form.file_field :image %>
  <%= form.submit "SEND" , class:"form-btn"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "form", post: @post, url: post_path(@post.id)%>

app/views/posts/index.html.erb
<span class="rank-title" >最新の投稿</span>
<%= render 'contents', posts: @posts%>
<div class="page">
<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<%= render "form", post: @post, url: posts_path%>

app/views/posts/ranking.html.erb
<span class="rank-title">ハッシュタグランキング</span>
<div class = "rank-tags">
  <% @tags.each.with_index(1) do |tag, i|%>
    <div class = "rank">
      第<%=i%>位
    </div>
    <div class="rank-tag"><span class="hash">#</span><%=link_to tag, root_path(tag_name: tag.name), class:"rank-tag"%>
    </div>
  <% end %>
  </div>
<span class="rank-title">いいね数ランキング</span>
<div class = "contents-rank">

  <% @like_posts.each.with_index(1) do |post, i|%>
    <div class="rank"> 第<%= i  %>位 </div>
      <div class="content-rank">
        <div class="top-content">
          <h2><%= post.title%></h2>
          <%= link_to post.user.name, user_path(post.user_id), class:"user"%></a>
        </div>
        <div class="play-list">
          <div class="left-contents">
            <%if post.image.present?%>
              <%= link_to (image_tag (post.image),class: "list-img"), post_path(post.id) %>
            <%end%>
            <% post.tag_list.each do |tag| %>
              <div class="hash-name">
                <span class = "hash" >#</span><%= link_to tag, root_path(tag_name: tag), class:"user" %>
              </div>
            <%end%>
          </div>
          <ul class="musics">
            <%post.musics.first(10).each do |music|%>
              <li><%=music.track%></li>
            <%end%>
          </ul>
        </div>
        <% if user_signed_in?%>
          <div id="likes_btn_<%=post.id%>" >
            <%= render "likes/like", post: post%>
          </div>
        <%else%>
          <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
          <span class="like"><%= post.likes.count %></span>
        <%end%>
      </div>
    <% end %>
</div>

app/views/posts/search.html.erb
<% if @posts.present?%>
  <%= render 'contents', posts: @posts%>
<% else %>
  <h1 class="show-text">検索結果はありませんでした。</h1>
<% end %>

app/views/posts/show.html.erb
<div class="contents-show">
  <div class="content-show">
    <div class="top-content-show">
      <h2 class="title-show"><%= @post.title %></h2>
      <div class="user-show">
      <%= link_to "by #{@post.user.name}",user_path(@post.user_id), class:"show-name"%>
      <% if @post.user.image.present?%>
      <%=image_tag @post.user.image.variant(resize: '50x50'), class:"user-icon"%>
      <%end%>
      </div>
    </div>
    <% if user_signed_in? && current_user.id == @post.user_id %>
    <div class="more-show">
      <%= link_to "編集",edit_post_path(@post.id), class:"edit"%>
      <%= link_to "削除",post_path(@post.id), method: :delete, class:"edit"%>
    </div>
    <% end %>
      <%if @post.image.present?%>
        <%= link_to (image_tag (@post.image),class: "list-img-show"), post_path(@post.id) %>
      <%end%>
      <div class="link-show">
        <%= link_to "spotifyで聴く", @post.url, class:"text-show"%>
      </div>
    <div class="hash-name-show">
      <% @post.tag_list.each do |tag| %>
        <span class = "hash" >#</span><%= link_to tag, root_path(tag_name: tag), class:"tag-show" %>
      <%end%>
    </div>
    <ul class="musics-show">
      <% @post.musics.each do |music|%>
        <li><%= music.track %></li>
      <%end%>
    </ul>
    <div class= "bottom-contents-show">
      <%if user_signed_in?%>
      <div id="likes_btn_<%=@post.id%>" >
        <%= render "likes/like", post: @post%>
      </div>
      <%else%>
        <i class="fa fa-heart fa-2x" aria-hidden="true" style="color: gray;"></i>
        <span class="like"><%= @post.likes.count %></span>
      <%end%>
      <a href="https://twitter.com/intent/tweet?text=ShareMusicから共有[<%=@post.title%>]%0d&hashtags=<%=@post.tag_list[0]%>,ShareMusic%0d&url=https://share-music.herokuapp.com/posts/<%=@post.id%>">
        <i class="fab fa-twitter fa-2x twitter" aria-hidden="true" style="color: #00acee;"></i>
      </a>
      <div class="line-it-button" data-lang="ja" data-type="share-b" data-ver="3" data-url="https://share-music.herokuapp.com/posts/<%=@post.id%>" data-color="default" data-size="small" data-count="false" style="display: none;"></div>
      <script src="https://www.line-website.com/social-plugins/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
      </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class="top-contents">
  <nav id='nav'>
      <ul>
        <% if user_signed_in? %>
        <p class="greeting">こんにちは<%=current_user.name%>さん<p>
          <li>
            <%= link_to "新規投稿", new_post_path, class:"user-btn" %>
          </li>
          <li>
            <%= link_to "マイページ", user_path(current_user.id) %>
          </li>
          <li>
            <%= link_to "ユーザー情報編集", edit_user_registration_path(current_user.id) %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: "DELETE", class:"user-btn" %>
          </li>
      <% else %>
        <li>
          <%= link_to "ログイン", new_user_session_path, class: "user-btn" %>
        </li>
        <li>
          <%= link_to "新規登録", new_user_registration_path, class:"user-btn" %>
        </li>
      <% end %>
    </ul>
  </nav>
  <div id="hamburger">
      <span class="inner_line" id="line1"></span>
      <span class="inner_line" id="line2"></span>
      <span class="inner_line" id="line3"></span>
  </div>
    <%= link_to "Share Music", root_path , class:"logo" %>
    <%= link_to "Ranking", ranking_posts_path, class: "top-var" %>
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿、タグ、曲を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
    <% flash.each do |message_type, message| %>
      <%if message_type == "alert" || message_type == "notice"%>
        <div class = "flash">
          <span class="message"><%= message %></span>
        </div>
      <% end %>
    <% end %>
</header>

app/views/users/show.html.erb
<% if @user.id ==current_user.id %>
  <h1 class = "user-text">あなたの投稿です<h1>
  <% if @posts.present?%>
    <%= render "posts/contents", posts: @posts%>
  <% else %>
    <h1 class="show-text">まだ投稿はありません。<br>投稿してみましょう！</h1>
  <% end %>
  <h1 class = "user-text">あなたがいいねした投稿です<h1>
  <% if @likes.present?%>
    <div class = "like-contents">
      <% @likes.each do |post|%>
          <div class="like-content">
            <div class="top-content">
              <h2><%= post.title%></h2>
              <%= link_to post.user.name, user_path(post.user_id), class:"user"%></a>
            </div>
            <div class="play-list">
              <div class="left-contents">
                <%if post.image.present?%>
                  <%= link_to (image_tag (post.image),class: "list-img"), post_path(post.id) %>
                <%end%>
                <% post.tag_list.each do |tag| %>
                  <div class="hash-name">
                    <span class = "hash" >#</span><%= link_to tag, root_path(tag_name: tag), class:"user" %>
                  </div>
                <%end%>
              </div>
              <ul class="like-musics">
                <%post.musics.first(10).each do |music|%>
                  <li class="like-music"><%= music.track%></li>
                <%end%>
              </ul>
            </div>
            <% if user_signed_in?%>
              <div id="like_btn_<%=post.id%>" >
                <%= render "likes/like", post: post%>
              </div>
            <%else%>
              <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
              <span class="like"><%= post.likes.count %></span>
            <% end %>
          </div>
      <% end %>
    </div>
    <% else %>
    <h1 class="show-text">あなたがいいねした投稿はありません</h1>
  <% end %>
<%else%>

  <h1 class = "user-text"><%=@user.name%>さんの投稿です<h1>
  <% if @posts.present?%>
    <%= render "posts/contents", posts: @posts%>
  <% else %>
    <h1 class="show-text"><%=@user.name%>さんの投稿はありません</h1>
  <% end %>

  <h1 class = "user-text"><%=@user.name%>さんがいいねした投稿です<h1>
  <% if @likes.present?%>
    <div class = "like-contents">
      <% @likes.each do |post|%>
          <div class="like-content">
            <div class="top-content">
              <h2><%= post.title%></h2>
              <%= link_to post.user.name, user_path(post.user_id), class:"user"%></a>
            </div>
            <div class="play-list">
              <div class="left-contents">
                <%if post.image.present?%>
                  <%= link_to (image_tag (post.image),class: "list-img"), post_path(post.id) %>
                <%end%>
                <% post.tag_list.each do |tag| %>
                  <div class="hash-name">
                    <span class = "hash" >#</span><%= link_to tag, root_path(tag_name: tag), class:"user" %>
                  </div>
                <%end%>
              </div>
              <ul class="like-musics">
                <%post.musics.first(10).each do |music|%>
                  <li class="like-music"><%= music.track%></li>
                <%end%>
              </ul>
            </div>
            <% if user_signed_in?%>
              <div id="like_btn_<%=post.id%>" >
                <%= render "likes/like", post: post%>
              </div>
            <%else%>
              <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
              <span class="like"><%= post.likes.count %></span>
            <% end %>
          </div>
      <% end %>
    </div>
    <% else %>
    <h1 class="show-text"><%=@user.name%>さんがいいねした投稿はありません</h1>
  <% end %>
<% end %>